app = "fx9-dashboard"

[build]
  builder = "heroku/buildpacks:20"

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1

[mounts]
  source = "dashdata"
  destination = "/data"